# Generated by Django 5.2.6 on 2025-09-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PiImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='pi_images/%Y/%m/%d/')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('received', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
